image: python:3.10

before_script:
  - python3 -m pip install pipenv
  - pipenv install --dev

stages:
  - Code Check
  - Test

python-black:
  stage: Code Check
  script:
    - pipenv run python3 -m black --check --diff .
  allow_failure: false

python-flake8:
  stage: Code Check
  script:
    - pipenv run python3 -m flake8 .
  allow_failure: false

python-mypy:
  stage: Code Check
  script:
    - pipenv run python3 -m mypy .
  allow_failure: false

python-isort:
  stage: Code Check
  script:
    - pipenv run python3 -m isort --profile black --check-only .
  allow_failure: false

tests:
  stage: Test
  script:
    - pipenv run python3 -m pytest --cov .
  allow_failure: false
