name: "Prepare env"
runs:
    using: "composite"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install pipenv and dependencies
        shell: bash
        run: |
          python3 -m pip install pipenv==2022.10.12
          pipenv install -d
